# app/services/report_generator.py
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from datetime import datetime
import os

def generate_fir_report(features: dict, risk_data: dict, output_path: str = None):
    """Generate a professional FIR PDF report"""
    
    if output_path is None:
        os.makedirs("reports", exist_ok=True)
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        output_path = f"reports/LUMINA_FIR_{timestamp}.pdf"
    
    c = canvas.Canvas(output_path, pagesize=A4)
    width, height = A4
    y = height - 50
    
    # Header
    c.setFont("Helvetica-Bold", 24)
    c.setFillColorRGB(0.2, 0.3, 0.7)
    c.drawString(50, y, "🚨 LUMINA")
    c.setFont("Helvetica", 12)
    c.setFillColorRGB(0.5, 0.5, 0.5)
    c.drawString(160, y, "Digital Arrest Scam Report")
    y -= 40
    
    # Report ID
    c.setFont("Helvetica-Bold", 11)
    c.setFillColorRGB(0, 0, 0)
    c.drawString(50, y, f"Report ID: LUMINA-{datetime.now().strftime('%Y%m%d')}-001")
    c.drawString(400, y, f"Date: {datetime.now().strftime('%B %d, %Y')}")
    y -= 25
    
    # Divider
    c.line(50, y, 550, y)
    y -= 20
    
    # Section 1: Call Details
    c.setFont("Helvetica-Bold", 14)
    c.setFillColorRGB(0.2, 0.3, 0.7)
    c.drawString(50, y, "📞 Call Details")
    y -= 25
    
    c.setFont("Helvetica", 11)
    c.setFillColorRGB(0, 0, 0)
    details = [
        f"Duration: {features.get('call_duration_min', 0):.0f} minutes",
        f"Unknown Number: {'Yes' if features.get('is_unknown_number', 0) else 'No'}",
        f"Video Call: {'Yes' if features.get('is_video_call', 0) else 'No'}",
        f"Time of Day: {features.get('hour_of_day', 0)}:00",
        f"Prior Calls: {features.get('caller_call_history', 0)}",
        f"Outgoing Activity: {features.get('outgoing_activity_ratio', 0):.2f}"
    ]
    for line in details:
        c.drawString(70, y, f"• {line}")
        y -= 18
    y -= 10
    
    # Section 2: Risk Assessment
    c.setFont("Helvetica-Bold", 14)
    c.setFillColorRGB(0.2, 0.3, 0.7)
    c.drawString(50, y, "📊 Risk Assessment")
    y -= 25
    
    risk_level = risk_data.get('risk_level', 'low').upper()
    color = {"CRITICAL": (0.8, 0, 0), "HIGH": (0.9, 0.4, 0), 
             "MEDIUM": (0.9, 0.7, 0), "LOW": (0, 0.6, 0)}
    c.setFillColorRGB(*color.get(risk_level, (0, 0, 0)))
    c.setFont("Helvetica-Bold", 16)
    c.drawString(70, y, f"Risk Level: {risk_level}")
    y -= 20
    
    c.setFillColorRGB(0, 0, 0)
    c.setFont("Helvetica", 11)
    c.drawString(70, y, f"Risk Score: {risk_data.get('risk_score', 0)}/100")
    y -= 18
    c.drawString(70, y, f"Top Factors: {', '.join(risk_data.get('top_factors', ['None']))}")
    y -= 25
    
    # Section 3: Recommended Actions
    c.setFont("Helvetica-Bold", 14)
    c.setFillColorRGB(0.2, 0.3, 0.7)
    c.drawString(50, y, "⚡ Recommended Actions")
    y -= 25
    
    c.setFont("Helvetica", 11)
    c.setFillColorRGB(0, 0, 0)
    actions = [
        "1. Call the person on another line immediately",
        "2. Visit their home if possible",
        "3. If confirmed scam, dial 1930 (National Cyber Helpline)",
        "4. Report at cybercrime.gov.in",
        "5. Share this report with local police"
    ]
    for action in actions:
        c.drawString(70, y, action)
        y -= 18
    y -= 10
    
    # Section 4: Legal Notice
    c.setFillColorRGB(0.8, 0, 0)
    c.setFont("Helvetica-Bold", 10)
    c.drawString(50, y, "⚠️ LEGAL NOTICE:")
    y -= 15
    c.setFillColorRGB(0, 0, 0)
    c.setFont("Helvetica", 9)
    c.drawString(70, y, "Digital arrest has NO legal standing in India. No agency conducts")
    y -= 12
    c.drawString(70, y, "arrests over video call or demands payment via phone.")
    y -= 20
    
    # Footer
    c.setFont("Helvetica", 8)
    c.setFillColorRGB(0.5, 0.5, 0.5)
    c.drawString(50, 40, f"Generated by LUMINA v1.0 | {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    c.drawString(400, 40, "LUMINA - Illuminating the Digital Arrest Trap")
    
    c.save()
    return output_path